name: Deploy to salesforceleetcode org

on:
  push:
    branches:
      - main
    paths:
      - 'force-app/**'

jobs:
  Deploy-to-salesforceleetcode-environment:
    runs-on: ubuntu-latest
    environment: salesforceleetcode

    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Install Salesforce CLI
      - name: Install sfdx
        run: npm install --global @salesforce/cli

      - name: Installing sfdx git delta
        run: |
          echo Y | sf plugins install sfdx-git-delta
          sfdx plugins

      - name: Create delta packages
        run: |
          mkdir changed-sources
          sf sgd source delta --to HEAD --from HEAD~1 --output changed-sources/ --generate-delta --source force-app/

      - name: Sync Delta to Main Folder
        run: |
          # Sprawdzamy czy SGD faktycznie coś wygenerowało
          if [ -d "changed-sources/force-app" ]; then
            echo "Changes detected. Syncing delta to force-app..."
            
            # 1. Usuwamy stare pliki, by nie deployować całego repo (zostawiamy pustą strukturę)
            find force-app -mindepth 1 -maxdepth 1 -not -name ".git*" -exec rm -rf {} +
            
            # 2. Kopiujemy tylko zmienione pliki z delty do force-app
            cp -r changed-sources/force-app/* force-app/
            
            echo "Files to be deployed:"
            find force-app -type f
          else
            echo "No changes in force-app. Skipping sync."
          fi

      - name: Deploy to environment
        run: |
          echo "${{ secrets.JWT_SERVER_KEY }}" > server.key
          
          sf org login jwt \
            --username ${{ secrets.DEPLOYMENT_USER_NAME }} \
            --jwt-key-file server.key \
            --client-id ${{ secrets.CONSUMER_KEY }} \
            --instance-url ${{ vars.INSTANCE_URL }} \
            --set-default

          # Teraz deployujemy z folderu 'force-app', który CLI zna i akceptuje
          sf project deploy start \
            --source-dir force-app \
            --test-level RunLocalTests
